### PR TITLE
feat: setup config updator

### PR DESCRIPTION
**Pull request by STRRL**

### CODE REVIEW

**Comment by STRRL** [comment]
> The following users are mentioned in OWNERS file(s) but are untrusted for the following reasons. One way to make the user trusted is to add them as [members](https://github.com/orgs/chaos-mesh/people) of the chaos-mesh org. You can then trigger verification by writing `/verify-owners` in a comment.
> 
> * shivanshs9
>   
>   * User is not a member of the org. User is not a collaborator. Satisfy at least one of these conditions to make the user trusted.

/cc @shivanshs9, I have invited you as a member of chaos-mesh org. :)

**Comment by STRRL** [comment]
😅

**Comment by shivanshs9** [comment]
> > The following users are mentioned in OWNERS file(s) but are untrusted for the following reasons. One way to make the user trusted is to add them as [members](https://github.com/orgs/chaos-mesh/people) of the chaos-mesh org. You can then trigger verification by writing `/verify-owners` in a comment.
> > 
> > * shivanshs9
> >   
> >   * User is not a member of the org. User is not a collaborator. Satisfy at least one of these conditions to make the user trusted.
> 
> /cc @shivanshs9, I have invited you as a member of chaos-mesh org. :)

Thank you for inviting me @STRRL! 😄

**Pull request merged**
